apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bookreview-ssm
  namespace: bookreview
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/km-dev/db/username"
        objectType: "ssmparameter"
        objectAlias: DB_USERNAME
      - objectName: "/km-dev/db/password"
        objectType: "ssmparameter"
        objectAlias: DB_PASSWORD
      - objectName: "/km-dev/db/endpoint"
        objectType: "ssmparameter"
        objectAlias: DB_ENDPOINT
  secretObjects:
    - secretName: bookreview-db-ssm
      type: Opaque
      data:
        - key: DB_USERNAME
          objectName: DB_USERNAME
        - key: DB_PASSWORD
          objectName: DB_PASSWORD
        - key: DB_ENDPOINT
          objectName: DB_ENDPOINT
