apiVersion: v1
kind: Pod
metadata:
  name: secret-init
  namespace: bookreview
spec:
  serviceAccountName: br-sa
  containers:
  - name: secrets-store
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets"
      readOnly: true
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "bookreview-ssm"
